---
title: "Network Analysis - Exercise 1"
output: 
  github_document: default
  md_document: default
  pdf_document:
    latex_engine: xelatex
geometry: margin=1in
date: "2024-03-19"
---

## Import Libraries
```{r Setup}
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=60), format='latex', echo=TRUE)
library(tidyverse)
library(tidygraph)
library(ggraph)
library(readr)
library(dplyr)
library(igraph)
```

## Import Data
``` {r Data Import}
Connections <- read_csv("/Users/chien/Library/CloudStorage/OneDrive-McGillUniversity/5d_Network_Analysis/Exercise1/Connections.csv", skip = 2, show_col_types=FALSE)
```
## Employer Count

``` {r Employer Count}
employer_counts <- Connections %>% group_by(Company) %>% summarise(Count = n())

# View the summary
print(employer_counts)
```

## Total Count of Contacts
``` {r Count of Contacts}

# Total count
total_contacts <- nrow(Connections)
print(total_contacts)

```

## Creating Nodes and Edges

``` {r Nodes and Edges}

Connections$Label <- paste(Connections$`First Name`,substr(Connections$`Last Name`, 1, 1), sep = " ")

nodes_df <- distinct(Connections, Label, .keep_all = TRUE) %>%
  select(Label) %>%
  mutate(id = row_number())

# re-arrange label and names

# Assuming your DataFrame is named df and has columns 'label' and 'id'
nodes_df <- nodes_df[, c('id', 'Label')]

# Create edges based on shared current employer
edges_df <- Connections %>%
  select(Label, Company) %>%
  inner_join(Connections, by = "Company") %>%
  select(Label.x, Label.y) %>%
  filter(Label.x != Label.y) %>%
  unique()

# Map node ids to edges
edges_df <- edges_df %>%
  left_join(nodes_df, by = c("Label.x" = "Label")) %>%
  rename(source = id) %>%
  left_join(nodes_df, by = c("Label.y" = "Label")) %>%
  rename(target = id) %>%
  select(source, target)

# Introduce a count of occurrences as 'weight' for each (source, target) pair
edges_weighted <- edges_df %>%
  group_by(source, target) %>%
  summarise(weight = n(), .groups = "drop")

# 'edges_weighted' now contains the unique pairs of (source, target) with their weights
```


## Analyze Network with igraph

``` {r igraph}

# Assuming edges_weighted and nodes_df are already defined and g is created
g <- graph_from_data_frame(d=edges_weighted, vertices=nodes_df, directed=FALSE)

# Assign names from the 'Label' column in nodes_df to the vertex attribute 'name'
V(g)$name <- nodes_df$Label

# Plot Graph
par(mar=c(1, 1, 1, 1))

plot(g,
     layout = layout_with_kk(g),
     vertex.size = 10,
     vertex.label.cex = 0.5)

```


